#!/usr/bin/env python3
"""Generate README.md from entries/*.json."""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
ENTRIES_DIR = ROOT / "entries"

CATEGORIES = [
    ("ai-models",   "🤖 AI & Models"),
    ("agents",      "🕵️ AI Agents"),
    ("kernels",     "⚙️ Custom Kernels & Low-Level"),
    ("compilers",   "🔨 Compilers & Frontends"),
    ("dev-tools",   "🛠 Dev Tools & Debugging"),
    ("hw-system",   "🖥 Hardware & System"),
    ("cloud-infra", "☁️ Cloud & Orchestration"),
    ("riscv-arch",  "🔩 RISC-V & Architecture"),
    ("research",    "🔬 Research & Papers"),
    ("games-demos", "🎮 Games & Demos"),
    ("guides",      "📚 Guides, Tutorials & Education"),
]

# Ordering for affiliation tiers: lower value = higher in the list
# community (0) → affiliated (1) → official (2)
AFFILIATION_ORDER = {"community": 0, "affiliated": 1, "official": 2}

# Icons for each recognized link type
LINK_ICONS = {
    "repo": "📦", "article": "📝", "talk": "🎤", "video": "🎥",
    "website": "🌐", "demo": "🚀", "lesson": "📖", "paper": "📄",
}

# Shields.io badges for each affiliation tier
SHIELDS = {
    "community": "![community](https://img.shields.io/badge/community-27AE60?style=flat-square)",
    "affiliated": "![affiliated](https://img.shields.io/badge/affiliated-EC96B8?style=flat-square)",
    "official":   "![official](https://img.shields.io/badge/official-607D8B?style=flat-square)",
}


def load_entries():
    """Load all entry JSON files from ENTRIES_DIR, sorted by filename.

    Entries with ``"hidden": true`` are excluded so they remain in the JSON
    database for historical reference but do not appear in the generated README.
    """
    entries = [json.loads(f.read_text()) for f in sorted(ENTRIES_DIR.rglob("*.json"))]
    return [e for e in entries if not e.get("hidden") is True]


def sort_entries(entries):
    """Sort entries with community-first ordering.

    Primary key:   affiliation tier (community < affiliated < official)
    Secondary key: featured flag (featured entries come first within a tier)
    Tertiary key:  star count descending (more stars = higher rank)
    """
    def key(e):
        tier = AFFILIATION_ORDER.get(e.get("affiliation", "community"), 2)
        feat = 0 if e.get("featured") else 1
        return (tier, feat, -(e.get("stars", 0)))
    return sorted(entries, key=key)


def render_entry(e):
    """Render a single entry as a Markdown list item.

    Produces a block like:
        - **[name](repo_url)** ![badge]
          Description text.
          [📦 repo](url) · [🎤 FOSDEM 2026](url)
    """
    name = e["name"]
    desc = e["description"]
    badge = SHIELDS.get(e.get("affiliation", "community"), "")
    links = e.get("links", [])

    # Use the first repo link (if any) to hyperlink the project name
    repo = next((l for l in links if l["type"] == "repo"), None)
    name_md = f"[{name}]({repo['url']})" if repo else name

    # Build the inline link list; fall back to generic link icon for unknown types
    link_parts = [
        f"[{LINK_ICONS.get(l['type'], '🔗')} {l.get('label') or l['type']}]({l['url']})"
        for l in links
    ]
    result = f"- **{name_md}** {badge}\n  {desc}"
    if link_parts:
        result += f"\n  {' · '.join(link_parts)}"
    return result


def generate():
    """Build the full README string from all entries."""
    entries = sort_entries(load_entries())

    lines = [
        "# ⚡ Awesome Tenstorrent", "",
        "> A curated, community-first collection of awesome demos, tools, projects, and resources "
        "built by and for the Tenstorrent ecosystem.", "",
        "> **This file is auto-generated from `entries/*.json`. Do not edit directly — "
        "see [CONTRIBUTING.md](CONTRIBUTING.md) to add an entry.**", "",
        "## Contents", "",
    ]

    # Table of contents — only include categories that have at least one entry
    for slug, label in CATEGORIES:
        if any(slug in e.get("categories", []) for e in entries):
            # Derive a GitHub-compatible anchor from the label
            anchor = re.sub(r'[^\w\s-]', '', label.lower()).strip().replace(' ', '-')
            anchor = re.sub(r'-+', '-', anchor)
            lines.append(f"- [{label}](#{anchor})")
    lines.append("")

    # Per-category sections
    for slug, label in CATEGORIES:
        cat_entries = [e for e in entries if slug in e.get("categories", [])]
        if not cat_entries:
            continue
        lines += [f"## {label}", ""]
        for e in cat_entries:
            lines += [render_entry(e), ""]

    lines += ["---", "", "*Generated by `scripts/generate_readme.py`.*", ""]
    return "\n".join(lines)


def main():
    """Write the generated README to the repository root."""
    readme = generate()
    out = ROOT / "README.md"
    out.write_text(readme)
    print(f"Wrote {out}")


if __name__ == "__main__":
    main()
